### ISSUE TITLE
2captcha just keeps running "Start recaptcha solving", does not go to create accounts

### ISSUE THREAD

**Issue by ewigg** [sebastienvercammen/ptc-acc-gen#77]
Im using it with 2captcha, my first batch worked fine but on the second it only repeats "Start recaptcha solving", keeps going, been running for an hour or so. Is something wrong or is it just nobody that can solve it right now?

![ptcaccgen](https://cloud.githubusercontent.com/assets/6955113/18809556/bb4a0f66-827e-11e6-81cc-966f2ff77d76.JPG)

**Comment by FrostTheFox** [comment]
If I had to guess, recaptcha isn't giving a response or isn't giving a good response to the captcha.

**Comment by ewigg** [comment]
Thanks. I wait and try again tomorrow. https://2captcha.com/ is getting 502 bad gateway now, so it can be a problem on their side :/

**Comment by Scalpweb** [comment]
It happens when the 2captcha servers are down. I'd need to update my PR to enable better errors handling... I'll do that asap.

**Comment by FrostTheFox** [comment]
@Scalpweb <3

**Comment by FrostTheFox** [comment]
Not a huge bug, but still tagging.

**Comment by Scalpweb** [comment]
I said ASAP... Well, actually, I should have said "when i'll have some time". I'll try to check it tomorrow.

**Comment by Scalpweb** [comment]
Well, I cannot make it happen again... So nothing much to do right now

**Comment by kevintjuh93** [comment]
I got this error and it's really annoying... it also consumes my money :( any idea?

**Comment by sebastienvercammen** [comment]
This bug is very old and I was inactive during this time, but I've now added proper error handling on the first 2captcha request. If the initial request returns an error (e.g. invalid HTTP response), it'll stop.

As I've mentioned in another issue: I didn't write this part of the code (I was away because I was moving irl) and it should be rewritten entirely because this part is one big, ugly piece of code. I can't make any promises because I don't have much time lately, but any PRs are always welcome.
