### ISSUE TITLE
[Not ptc-acc-gen issue] Tutorial isn't completed (PogoPlayer issue)

### ISSUE THREAD

**Issue by Imoq** [sebastienvercammen/ptc-acc-gen#97]
As discussed in Discord, it seems like PogoPlayer has been broken for a while now. As ptc-acc-gen uses it to accept ToS (and used to complete the in-game tutorial) it would be good to modify it to either just accept the ToS or better to fix it to complete the tutorial again.

I've opened an issue on PogoPlayer (https://github.com/MRokas/PogoPlayer/issues/16) to which the author only acknowledged it has been like this "for months" now.

I looked at PoGoTos (https://github.com/TachyonRSA/PoGoTos), it seems to work but it's a simple code and has hard-coded initial login coordinates to NYC.

@sebastienvercammen mentioned he has an idea on how to fix PogoPlayer and potentially have a maintained/updated fork.

Thank you!

**Comment by sebastienvercammen** [comment]
Latest commit should fix this. Waiting on feedback.

**Comment by Imoq** [comment]
Just a quick note to remind the error was still there, but you mentioned in Discord that perhaps you knew how to solve the PogoPlayer issue.

Thank you!

**Comment by sebastienvercammen** [comment]
Correct, there's more to be fixed in PogoPlayer than just the outdated dependencies. I'm on it.

**Comment by sebastienvercammen** [comment]
It's been a while since my last comment on Github about this, but as mentioned via the PokémonGo-Map Discord, I've since reworked this entire functionality to integrate directly into the map so we no longer need  to rely on 3rd party scripts that eventually lose support.

The gen is also being reworked from scratch and the new version will reflect this change.
